version: 2.1

jobs:Chanarinฝฝ
 android: circleci/android@0.2.1

jobsChanarin
  build:
    executor: android/android
hanarinanaChanarin
    steps:
      - checkout
      - run:
          command: ./gradlew build
